language: csharp
sudo: required
dist: trusty # Ubuntu 14.04

env:
  - HOME=/home/travis APPDATA=/home/travis LocalAppData=/home/travis TRAVIS_STAGE=0 # DISABLE_NETCORE=true
  # - HOME=/home/travis APPDATA=/home/travis LocalAppData=/home/travis TRAVIS_STAGE=1 # DISABLE_NETCORE=true

addons:
  apt:
    packages:
      - libunwind8
      - msbuild
  
before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force openssl ; fi

mono:
  - 5.4.1

script: 
#  - fake run build.fsx
  - ./build.sh
  - ./build.sh test
  - ./build.sh BDD

branches:
  except:
    - gh-pages